### ISSUE TITLE
As an admin I want to be able to generate monthly statement responses , so that I would be able to keep track of the lunch box menu and see if there are any updated items in the menu.

### ISSUE THREAD

**Issue by AzadAkimAhamed** [AzadAkimAhamed/C206_CaseStudy#11]

**Comment by Ridzwana25** [comment]
Given that i have the ability to generate monthly statement based on the food menu served each month  When i generate the monthly statement report of the food items  Then the report would show the food items which was served for each month respectively and thus , after that we are also able to generate statistics for research purposes when we have to make an decision if we want to keep that food items in the menu or changed it into another item which would further increase students preferences and from there we can determine the best choices for students both in primary and secondary schools  Priority: Could have Story point: 3  Acceptance Criteria : The generated report would have to be done monthly , up to date and with the required changes if needed. generated report have to show each set of meals which was set for each day.
